Metrics/MethodLength:
  Max: 12

Metrics/ModuleLength:
  Max: 150

Style/ModuleFunction:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/FileName:
  Enabled: false

AllCops:
  Include:
    - lib/